#!/usr/bin/env node
// ============================================================
// gen-vapid — generate the VAPID key pair for browser push
// (spec round 2 §5).
//
// Prints three lines ready to paste into `.env.local` /
// `.env.production`:
//
//   NEXT_PUBLIC_VAPID_PUBLIC_KEY=...   (public; shipped to the browser)
//   VAPID_PRIVATE_KEY=...              (secret; server only)
//   VAPID_SUBJECT=mailto:...           (contact for the push service)
//
// Usage:
//   node scripts/gen-vapid.mjs                   # print to stdout
//   node scripts/gen-vapid.mjs >> .env.local     # append to the env file
//   node scripts/gen-vapid.mjs --subject mailto:ops@example.com
//
// Rotating the keys invalidates every stored subscription: users have
// to enable notifications again in Configurações → Notificações.
// ============================================================

import webpush from 'web-push'

const args = process.argv.slice(2)
const subjectIdx = args.indexOf('--subject')
const subject =
  subjectIdx >= 0 && args[subjectIdx + 1]
    ? args[subjectIdx + 1]
    : 'mailto:admin@semprecrm.local'

if (!/^(mailto:|https:\/\/)/.test(subject)) {
  console.error('VAPID_SUBJECT must be a mailto: address or an https:// URL')
  process.exit(1)
}

const { publicKey, privateKey } = webpush.generateVAPIDKeys()

process.stdout.write(
  [
    '',
    '# Web Push (VAPID) — generated by scripts/gen-vapid.mjs',
    `NEXT_PUBLIC_VAPID_PUBLIC_KEY=${publicKey}`,
    `VAPID_PRIVATE_KEY=${privateKey}`,
    `VAPID_SUBJECT=${subject}`,
    '',
  ].join('\n'),
)
