-- ============================================================
-- 029_lead_sources.sql — Lead capture by webhook (module
-- `lead_capture`): one public inbound endpoint per "source"
-- (landing page, form, Zapier, n8n…) that turns a payload into
-- contact + deal + tags and fires automations.
--
-- Spec: docs/superpowers/specs/2026-09-13-parity-round1-design.md
--       section "2. Captura de leads por webhook"
--
-- What this migration does
--   1. Creates `lead_sources` — name, secret token (32 bytes hex,
--      generated by the app server, unique), routing (pipeline →
--      stage, tags, assignee), `field_map` (CRM field ← payload
--      key), counters.
--   2. Creates `lead_source_events` — one row per received
--      payload with status ok / duplicate / error. Index on
--      (source_id, created_at desc). The cron deletes rows older
--      than 90 days.
--   3. RLS: viewer+ reads both tables; admin+ writes sources;
--      events are written only by the service role (the route).
--   4. Adds `lead_capture` to the modules `platform_update_account`
--      accepts in `module_overrides` (keep in sync with
--      OPTIONAL_MODULES in src/lib/plans.ts). Body is 027's, with
--      the new module in `v_allowed_modules`.
--
-- Does NOT touch `handle_new_user`.
-- Idempotent — safe to run multiple times.
-- ============================================================

-- ============================================================
-- LEAD_SOURCES
-- ============================================================
CREATE TABLE IF NOT EXISTS lead_sources (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  account_id        UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  name              TEXT NOT NULL,
  token             TEXT NOT NULL,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  pipeline_id       UUID REFERENCES pipelines(id) ON DELETE SET NULL,
  stage_id          UUID REFERENCES pipeline_stages(id) ON DELETE SET NULL,
  tag_ids           UUID[] NOT NULL DEFAULT '{}',
  assignee_user_id  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  field_map         JSONB NOT NULL DEFAULT '{}'::jsonb,
  received_count    INTEGER NOT NULL DEFAULT 0,
  last_received_at  TIMESTAMPTZ,
  created_by        UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE lead_sources DROP CONSTRAINT IF EXISTS lead_sources_name_check;
ALTER TABLE lead_sources ADD CONSTRAINT lead_sources_name_check
  CHECK (length(btrim(name)) > 0);

-- The token is the only credential a caller presents; it must be
-- globally unique so a lookup by token resolves to one account.
ALTER TABLE lead_sources DROP CONSTRAINT IF EXISTS lead_sources_token_key;
ALTER TABLE lead_sources ADD CONSTRAINT lead_sources_token_key UNIQUE (token);

ALTER TABLE lead_sources DROP CONSTRAINT IF EXISTS lead_sources_token_format_check;
ALTER TABLE lead_sources ADD CONSTRAINT lead_sources_token_format_check
  CHECK (token ~ '^[0-9a-f]{64}$');

ALTER TABLE lead_sources DROP CONSTRAINT IF EXISTS lead_sources_field_map_object_check;
ALTER TABLE lead_sources ADD CONSTRAINT lead_sources_field_map_object_check
  CHECK (jsonb_typeof(field_map) = 'object');

CREATE INDEX IF NOT EXISTS idx_lead_sources_account ON lead_sources(account_id, created_at);

DROP TRIGGER IF EXISTS set_updated_at ON lead_sources;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON lead_sources
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE lead_sources ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS lead_sources_select ON lead_sources;
CREATE POLICY lead_sources_select ON lead_sources FOR SELECT
  USING (is_account_member(account_id));
DROP POLICY IF EXISTS lead_sources_insert ON lead_sources;
CREATE POLICY lead_sources_insert ON lead_sources FOR INSERT
  WITH CHECK (is_account_member(account_id, 'admin'));
DROP POLICY IF EXISTS lead_sources_update ON lead_sources;
CREATE POLICY lead_sources_update ON lead_sources FOR UPDATE
  USING (is_account_member(account_id, 'admin'))
  WITH CHECK (is_account_member(account_id, 'admin'));
DROP POLICY IF EXISTS lead_sources_delete ON lead_sources;
CREATE POLICY lead_sources_delete ON lead_sources FOR DELETE
  USING (is_account_member(account_id, 'admin'));

-- ============================================================
-- LEAD_SOURCE_EVENTS
-- ============================================================
CREATE TABLE IF NOT EXISTS lead_source_events (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  account_id  UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  source_id   UUID NOT NULL REFERENCES lead_sources(id) ON DELETE CASCADE,
  status      TEXT NOT NULL,
  error       TEXT,
  contact_id  UUID REFERENCES contacts(id) ON DELETE SET NULL,
  deal_id     UUID REFERENCES deals(id) ON DELETE SET NULL,
  payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE lead_source_events DROP CONSTRAINT IF EXISTS lead_source_events_status_check;
ALTER TABLE lead_source_events ADD CONSTRAINT lead_source_events_status_check
  CHECK (status IN ('ok', 'duplicate', 'error'));

CREATE INDEX IF NOT EXISTS idx_lead_source_events_source_created
  ON lead_source_events(source_id, created_at DESC);
-- The retention sweep in /api/automations/cron deletes by age.
CREATE INDEX IF NOT EXISTS idx_lead_source_events_created ON lead_source_events(created_at);

ALTER TABLE lead_source_events ENABLE ROW LEVEL SECURITY;

-- Members read; nobody writes through RLS — the webhook route uses the
-- service role, which bypasses these policies.
DROP POLICY IF EXISTS lead_source_events_select ON lead_source_events;
CREATE POLICY lead_source_events_select ON lead_source_events FOR SELECT
  USING (is_account_member(account_id));

-- ============================================================
-- platform_update_account — 027 body + `lead_capture` as an
-- overridable module (keep `v_allowed_modules` in sync with
-- OPTIONAL_MODULES in src/lib/plans.ts).
-- ============================================================
DROP FUNCTION IF EXISTS public.platform_update_account(UUID, JSONB);
CREATE OR REPLACE FUNCTION public.platform_update_account(
  p_account_id UUID,
  p_patch JSONB
) RETURNS accounts
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row     accounts;
  v_key     TEXT;
  v_val     JSONB;
  v_allowed_modules TEXT[] := ARRAY[
    'dashboard', 'pipelines', 'tasks', 'broadcasts', 'automations', 'flows',
    'channel_official', 'channel_qr', 'lead_capture'
  ];
  v_allowed_limits TEXT[] := ARRAY['max_users', 'max_channels'];
BEGIN
  IF NOT is_platform_admin() THEN
    RAISE EXCEPTION 'Platform admin only' USING ERRCODE = '42501';
  END IF;

  IF p_patch IS NULL OR jsonb_typeof(p_patch) <> 'object' THEN
    RAISE EXCEPTION 'patch must be a JSON object' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_row FROM accounts WHERE id = p_account_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Account not found' USING ERRCODE = '22023';
  END IF;

  -- plan --------------------------------------------------------
  IF p_patch ? 'plan' THEN
    IF jsonb_typeof(p_patch->'plan') <> 'string'
       OR (p_patch->>'plan') NOT IN ('trial', 'basico', 'pro', 'empresa') THEN
      RAISE EXCEPTION 'plan must be one of trial, basico, pro, empresa'
        USING ERRCODE = '22023';
    END IF;
    v_row.plan := p_patch->>'plan';
  END IF;

  -- plan_status -------------------------------------------------
  IF p_patch ? 'plan_status' THEN
    IF jsonb_typeof(p_patch->'plan_status') <> 'string'
       OR (p_patch->>'plan_status') NOT IN ('trial', 'active', 'past_due', 'canceled', 'suspended') THEN
      RAISE EXCEPTION 'plan_status must be one of trial, active, past_due, canceled, suspended'
        USING ERRCODE = '22023';
    END IF;
    v_row.plan_status := p_patch->>'plan_status';
  END IF;

  -- plan_expires_at (null clears) --------------------------------
  IF p_patch ? 'plan_expires_at' THEN
    IF jsonb_typeof(p_patch->'plan_expires_at') = 'null' THEN
      v_row.plan_expires_at := NULL;
    ELSIF jsonb_typeof(p_patch->'plan_expires_at') = 'string' THEN
      BEGIN
        v_row.plan_expires_at := (p_patch->>'plan_expires_at')::timestamptz;
      EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'plan_expires_at must be an ISO-8601 timestamp or null'
          USING ERRCODE = '22023';
      END;
    ELSE
      RAISE EXCEPTION 'plan_expires_at must be an ISO-8601 timestamp or null'
        USING ERRCODE = '22023';
    END IF;
  END IF;

  -- module_overrides: {module: boolean} over the known modules ---
  IF p_patch ? 'module_overrides' THEN
    v_val := p_patch->'module_overrides';
    IF v_val IS NULL OR jsonb_typeof(v_val) <> 'object' THEN
      RAISE EXCEPTION 'module_overrides must be a JSON object' USING ERRCODE = '22023';
    END IF;
    FOR v_key IN SELECT jsonb_object_keys(v_val) LOOP
      IF NOT (v_key = ANY (v_allowed_modules)) THEN
        RAISE EXCEPTION 'Unknown module in module_overrides: %', v_key
          USING ERRCODE = '22023';
      END IF;
      IF jsonb_typeof(v_val->v_key) <> 'boolean' THEN
        RAISE EXCEPTION 'module_overrides.% must be true or false', v_key
          USING ERRCODE = '22023';
      END IF;
    END LOOP;
    v_row.module_overrides := v_val;
  END IF;

  -- limit_overrides: {max_users|max_channels: int >= 0 | null} ---
  IF p_patch ? 'limit_overrides' THEN
    v_val := p_patch->'limit_overrides';
    IF v_val IS NULL OR jsonb_typeof(v_val) <> 'object' THEN
      RAISE EXCEPTION 'limit_overrides must be a JSON object' USING ERRCODE = '22023';
    END IF;
    FOR v_key IN SELECT jsonb_object_keys(v_val) LOOP
      IF NOT (v_key = ANY (v_allowed_limits)) THEN
        RAISE EXCEPTION 'Unknown limit in limit_overrides: %', v_key
          USING ERRCODE = '22023';
      END IF;
      IF jsonb_typeof(v_val->v_key) NOT IN ('number', 'null') THEN
        RAISE EXCEPTION 'limit_overrides.% must be a number or null', v_key
          USING ERRCODE = '22023';
      END IF;
      IF jsonb_typeof(v_val->v_key) = 'number'
         AND ((v_val->>v_key)::numeric < 0 OR (v_val->>v_key)::numeric <> floor((v_val->>v_key)::numeric)) THEN
        RAISE EXCEPTION 'limit_overrides.% must be a non-negative integer', v_key
          USING ERRCODE = '22023';
      END IF;
    END LOOP;
    v_row.limit_overrides := v_val;
  END IF;

  -- platform_notes (null clears) ---------------------------------
  IF p_patch ? 'platform_notes' THEN
    IF jsonb_typeof(p_patch->'platform_notes') = 'null' THEN
      v_row.platform_notes := NULL;
    ELSIF jsonb_typeof(p_patch->'platform_notes') = 'string' THEN
      v_row.platform_notes := NULLIF(btrim(p_patch->>'platform_notes'), '');
    ELSE
      RAISE EXCEPTION 'platform_notes must be a string or null' USING ERRCODE = '22023';
    END IF;
  END IF;

  UPDATE accounts
  SET plan             = v_row.plan,
      plan_status      = v_row.plan_status,
      plan_expires_at  = v_row.plan_expires_at,
      module_overrides = v_row.module_overrides,
      limit_overrides  = v_row.limit_overrides,
      platform_notes   = v_row.platform_notes
  WHERE id = p_account_id
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

ALTER FUNCTION public.platform_update_account(UUID, JSONB) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.platform_update_account(UUID, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.platform_update_account(UUID, JSONB) TO authenticated, service_role;
